name = "my-first-nextjs-on-cf-pages"
compatibility_date = "2024-08-13"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[r2_buckets]]
binding = 'MY_BUCKET'
bucket_name = 'my-bucket-for-nextjs'